# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: webapp454   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "application"      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build:
    name: Build Node App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    # Build and test the project
    - name: npm install, build, and test
      run: |
        cd application
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Run unit tests
      continue-on-error: false
      run: |
        cd tests
        npm install
        gulp unittest

    - name: Creating artifact directories
      run: |
        mkdir buildartifacts
    # Archive build artifact
    - name: Archive Application
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./buildartifacts/application.zip ./application
    # Uploading application to build artifact
    - name: Upload Application to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts


    # print git run numbers
    - name: Print Run ID
      run: echo "Run ID ${{ github.run_id }}"
    - name: Print Run Number
      run: echo "Hello ${{ github.run_number }}"
    - name: Print Run Attempt
      run: echo "Hello ${{ github.run_attempt }}"
      
